"""Attendance admin views — logs (read-only) and records (editable status)."""

from datetime import datetime, timezone

from admin.base_views import ReadOnlyAdminView, SecureModelView


class AttendanceLogAdmin(ReadOnlyAdminView):
    """Read-only view for ``AttendanceLog`` entries.

    Attendance logs are system-generated by the face-recognition module;
    they should never be edited through the admin panel.
    """

    # ── List view ─────────────────────────────────────────────────────
    column_list = [
        "log_id",
        "student",
        "session_id",
        "event_type",
        "timestamp",
        "confidence_score",
    ]
    column_sortable_list = [
        "log_id",
        "event_type",
        "timestamp",
        "confidence_score",
    ]
    column_filters = ["event_type", "session_id", "timestamp"]
    column_default_sort = ("timestamp", True)

    # ── Labels ────────────────────────────────────────────────────────
    column_labels = {
        "log_id": "Log ID",
        "student": "Student",
        "session_id": "Session",
        "event_type": "Event",
        "timestamp": "Timestamp",
        "confidence_score": "Confidence",
    }

    # ── Relationship display ──────────────────────────────────────────
    column_formatters = {
        "student": lambda v, c, m, n: (
            m.student.roll_number if m.student else "—"
        ),
        "timestamp": lambda v, c, m, n: (
            m.timestamp.strftime("%Y-%m-%d %H:%M:%S") if m.timestamp else ""
        ),
    }


class AttendanceRecordAdmin(SecureModelView):
    """Admin view for ``AttendanceRecord`` — finalized attendance results.

    Admins can edit the ``status`` field to perform manual overrides
    (reuses the same concept as ``PUT /api/attendance/manual-override``).
    """

    can_create = False

    # ── List view ─────────────────────────────────────────────────────
    column_list = [
        "record_id",
        "student",
        "session_id",
        "status",
        "total_duration_seconds",
        "threshold_required",
        "finalized_at",
    ]
    column_sortable_list = [
        "record_id",
        "status",
        "total_duration_seconds",
        "finalized_at",
    ]
    column_searchable_list = ["session_id"]
    column_filters = ["status", "session_id"]
    column_default_sort = ("record_id", True)

    # ── Labels ────────────────────────────────────────────────────────
    column_labels = {
        "record_id": "Record ID",
        "student": "Student",
        "session_id": "Session",
        "status": "Status",
        "total_duration_seconds": "Duration (s)",
        "threshold_required": "Threshold (s)",
        "finalized_at": "Finalized At",
    }

    # ── Relationship display ──────────────────────────────────────────
    column_formatters = {
        "student": lambda v, c, m, n: (
            m.student.roll_number if m.student else "—"
        ),
        "finalized_at": lambda v, c, m, n: (
            m.finalized_at.strftime("%Y-%m-%d %H:%M") if m.finalized_at else "—"
        ),
    }

    # ── Form ──────────────────────────────────────────────────────────
    form_widget_args = {
        "record_id": {"disabled": True},
        "total_duration_seconds": {"disabled": True},
        "threshold_required": {"disabled": True},
        "finalized_at": {"disabled": True},
    }
    form_excluded_columns = ["student", "session"]

    def on_model_change(self, form, model, is_created):
        """Set finalized_at when status is changed through admin panel."""
        model.finalized_at = datetime.now(timezone.utc)
